/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutReviewRouteImport } from './routes/_pathlessLayout/review'
import { Route as PathlessLayoutOverviewRouteImport } from './routes/_pathlessLayout/overview'
import { Route as PathlessLayoutFocusRouteImport } from './routes/_pathlessLayout/focus'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutReviewRoute = PathlessLayoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutOverviewRoute = PathlessLayoutOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutFocusRoute = PathlessLayoutFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/focus': typeof PathlessLayoutFocusRoute
  '/overview': typeof PathlessLayoutOverviewRoute
  '/review': typeof PathlessLayoutReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/focus': typeof PathlessLayoutFocusRoute
  '/overview': typeof PathlessLayoutOverviewRoute
  '/review': typeof PathlessLayoutReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_pathlessLayout/focus': typeof PathlessLayoutFocusRoute
  '/_pathlessLayout/overview': typeof PathlessLayoutOverviewRoute
  '/_pathlessLayout/review': typeof PathlessLayoutReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/focus' | '/overview' | '/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/focus' | '/overview' | '/review'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/about'
    | '/login'
    | '/_pathlessLayout/focus'
    | '/_pathlessLayout/overview'
    | '/_pathlessLayout/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/review': {
      id: '/_pathlessLayout/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof PathlessLayoutReviewRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/overview': {
      id: '/_pathlessLayout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof PathlessLayoutOverviewRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/focus': {
      id: '/_pathlessLayout/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof PathlessLayoutFocusRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutFocusRoute: typeof PathlessLayoutFocusRoute
  PathlessLayoutOverviewRoute: typeof PathlessLayoutOverviewRoute
  PathlessLayoutReviewRoute: typeof PathlessLayoutReviewRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutFocusRoute: PathlessLayoutFocusRoute,
  PathlessLayoutOverviewRoute: PathlessLayoutOverviewRoute,
  PathlessLayoutReviewRoute: PathlessLayoutReviewRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
